apiVersion: v1
kind: Service
metadata:
  name: backend-{{- include "my-chart.fullname" . -}}
spec:
  selector:
    app: {{ .Values.backend.service.selector.appName }}
  ports:
    - protocol: {{ .Values.backend.service.protocol }}
      port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
