apiVersion: v1
kind: Service
metadata:
  name: mysqldb-{{- include "my-chart.fullname" . -}}
spec:
  selector:
    app: {{ .Values.mysqldb.service.selector.appName }}
  ports:
    - protocol: {{ .Values.mysqldb.service.protocol }}
      port: {{ .Values.mysqldb.service.port }}